version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - api_data:/data
    expose:
      - "5000"
    command: gunicorn --workers 2 --bind 0.0.0.0:5000 "wsgi:app"
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=/api
    depends_on:
      - api

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - web_dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - web
      - api
    restart: unless-stopped

volumes:
  api_data:
  web_dist:
