services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build: ./api
    environment:
      DB_URL: postgresql+psycopg://$DB_USER:$DB_PASS@db:5432/$DB_NAME
      CA_PRIV_KEY: /keys/ssh_user_ca
      CA_PUB_KEY: /keys/ssh_user_ca.pub
      DEFAULT_CERT_TTL: 16h
      API_SECRET: ${API_SECRET}
    volumes:
      - ./ca-keys:/keys:ro
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 30

  web:
    build: ./web
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost/health"]
      interval: 10s
      timeout: 3s
      retries: 30

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - web
      - api
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost/health"]
      interval: 10s
      timeout: 3s
      retries: 30

volumes:
  db_data:
